import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const poppins = localFont({
  src: [
    { path: "../public/assets/fonts/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/assets/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/assets/fonts/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../public/assets/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
